### PR TITLE
Add initial DCC Resume support

### PR DESCRIPTION
**Pull request by vincentjames501**
I've been using this code for a while now with great success. Let's discuss if you have any concerns!

### CODE REVIEW

**Comment by emsquared** [comment]
Thank you for your submission.

I have some items I need to complete for the next update before I can give this my full attention. I have added a reminder on my Mac so that I do not forget.

**Comment by emsquared** [comment]
Follow up:

I have completed the work that I have needed to and will be reviewing how this pull request behaves over the weekend. I will let you know no later than Monday evening.

Thanks again.

**Comment by emsquared** [comment]
Thanks again for your contribution.

As you can see by 05fb770, I took your changes and took them even further.

If you want like any type of accreditation for your contribution, then let me know. I included some in the commit message itself.

**Comment by vincentjames501** [comment]
Thanks for taking the time to get this feature in. Textual is my favorite IRC client and this feature makes it much better!

**Pull request closed without merging**
