### PR TITLE
Only confirm quitting if connections are active

### PR DESCRIPTION
**Pull request by williamleuschner**
Hello!

This patch fixes a tiny thing that's been bugging me for a while now: Textual always asks for confirmation when quitting, even when there are no connections open and quitting isn't a destructive action. I've never written Objective-C before, so I don't know if this patch is the "most correct" way of solving the problem. I did test it though, and it builds and runs without errors or unexpected behavior.

Is this a change you'd be willing to accept?

(P.S. Thanks for developing Textual! It's my favorite IRC client.)

### CODE REVIEW

**Comment by emsquared** [comment]
Could you possibly resubmit this without the changes to the .xib file as I am a complete retard with git and don't want to merge that.

**Comment by dgw** [comment]
@williamleuschner You can rebase and force-push to undo the .xib changes, without opening a new PR.

I'd write instructions, but am very short on time. So, this will give you a chance to figure it out yourself I guess. If you get stuck I can take time to help you for real later.

@emsquared Happy to teach you at the same time, too, if you're interested. Rebasing is a useful skill. :)

**Comment by williamleuschner** [comment]
@emsquared Sure! Just did.

@dgw I typically work in a merge-heavy Git workflow, so I avoid rebases and force-pushes because they make the Git history less clear. I partially reverted the commit instead (and also messed up and needed to force-push to fix it anyway).

**Comment by emsquared** [comment]
Well I think I managed to merge it. :)

**Comment by dgw** [comment]
@williamleuschner That works too, if the maintainer doesn't mind revert commits! I'm used to projects preferring squashed/rebased PRs when possible.

**Comment by williamleuschner** [comment]
Ah, okay. Good to know, thanks!

**Pull request merged**
