### PR TITLE
I think the Russian interface of a chat is necessary.

### PR DESCRIPTION
**Pull request by tomfarrium**
I think the Russian interface of a chat is necessary. Though can do it and not so, but I have already a menu in Russian.
Just copy/paste files from the //Application/Textual 7⁩/⁨Contents⁩/⁨Resources/en.lproj to ⁩//Application/Textual 7⁩/⁨Contents⁩/⁨Resources/ru.lproj and replace the TXCMainMenu.nib to file from my repository. 

Enjoy Russian main Menu.

### CODE REVIEW

**Comment by tomfarrium** [comment]
Oh. soryy: May be developers add the other languages, to interface?

**Comment by tomfarrium** [comment]
I'm continue translate menu and interface to russian language

**Comment by eintw1ck** [comment]
I think best way is just to add your ru.lproj to `Sources/App/Resources/Language Files` in a commit whenever you're finished with translation

**Comment by tomfarrium** [comment]
My ru.lproj in - https://github.com/tomfarrium/Textual/tree/master/Sources/App/Resources/Language%20Files and modified files too

**Comment by tomfarrium** [comment]
The main language of a system has to be RU. Just unpack "https://github.com/tomfarrium/Textual/blob/master/ru.lproj.zip" to "//Application/Textual 7 ⁩/⁨ Contents ⁩/⁨ Resources/" and reboot the program.

**Pull request merged**
