### PR TITLE
quick & dirty patches for support BigSur and M1

### PR DESCRIPTION
**Pull request by serge-ivamov**
at least it works for me.
```
$ file Textual
Textual: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
Textual (for architecture x86_64):	Mach-O 64-bit executable x86_64
Textual (for architecture arm64):	Mach-O 64-bit executable arm64
```

### CODE REVIEW

**Comment by flying-sausages** [comment]
Any reproduction instructions? I'm getting stuck here 
image

**Comment by flying-sausages** [comment]
What I tried doing
1. Clone repo from scratch 
2. `gh pr checkout 544`
3. clone submodules
4. Change to standalone sandboxed
5. change signing to "sign to run locally"
6. Encounter build errors above

Are there any chance any changes to the frameworks that didn't get submitted here due to them being git submodules?

**Comment by serge-ivamov** [comment]
Try to make EncryptionKit.framework.

**Comment by flying-sausages** [comment]
Any chance you'd be so kind and elaborate? I'm not sure what you mean by `make` but when I switch the arch and try to build the framework on is own, I get `clang` compiler errors. I'm not educated enough in Obj-C to know how to fix that myself.

**Comment by serge-ivamov** [comment]
I don't have this project atm, I need to get it again and compile it.
I will try to do it on the weekend.

**Comment by serge-ivamov** [comment]
Frameworks/Encryption Kit - configured for x86_64, so need to build this framework for arm too.
Edit Frameworks/Encryption Kit/Resources/Build Configuration/Build Configuration.xcconfig
for ARCHS = $(ARCHS_STANDARD)
and build bundled C libraries for arm.

Unfortunately I deleted this project after getting a working binary, so my fixes for frameworks were not saved.

**Comment by jrtc27** [comment]
Perhaps it'd be better to use NSInvocation rather than raw objc_msgSend (which I believe is slightly different on GNUstep, FWIW)?

**Comment by serge-ivamov** [comment]
Maybe ... I don't know objc at all, so just copied the example from stackoverflow ... and it works somehow.

**Pull request closed without merging**
