### PR TITLE
Update TVCImageURLParser.m

### PR DESCRIPTION
**Pull request by jq1106**
Added support for i.leetfil.es links (direct images), and changed return url for video thumbnails.

### CODE REVIEW

**Comment by jq1106** [comment]
Forgot to check for if it's i.leetfil.es in the else, otherwise doing leetfil.es/mgiodsjiopgh would've triggered the image parser.

**Comment by emsquared** [comment]
Seems like having ``if ([host hasSuffix:@"i.leetfil.es"]) {`` at top level of if statement would make more sense instead of in ``} else {``

For example:  

```
	} else if ([host hasSuffix:@"leetfil.es"]) {
		...
	} else if ([host hasSuffix:@"i.leetfil.es"]) {
		...
```

I will accept the pull request either way. It appears the changes are reasonable, even with what I mentioned.

Let me know if you want to change that, otherwise ill merge now.

**Comment by jq1106** [comment]
Very true, I just wanted to contain it all in my own little section for leetfiles so that's why I put the || and the if in the else part. However now that I think about it I could change it to the if or, then specify an if and an else if. 

Two coffees so far and I'm still half asleep :P

**Comment by jq1106** [comment]
Ok, that looks better now :P

**Comment by emsquared** [comment]
Thank you

**Pull request merged**
