### PR TITLE
Added metadata to readme

### PR DESCRIPTION
**Pull request by oleander**
Hi!

I added some metadata to the readme. Feel free to make changes, like the print screen.

skarmavbild 2016-06-22 kl 23 54 49

### CODE REVIEW

**Comment by oleander** [comment]
Any status one this?

**Comment by emsquared** [comment]
Sorry for lack of reply. Been focusing all my attention on refactoring. I guarantee ill give this a close look on the weekend.

**Comment by emsquared** [comment]
I have taken a look at your modifications and made some of my own. I will present the modified version tomorrow because it is already fairly late where I am.

**Comment by emsquared** [comment]
I have committed the modified README. You can see the final result in the master branch.

If you have feedback regarding the changes I made myself, then please let me know.

Thank you for your contribution

**Pull request merged**
